controller_list:
 - name: follow_joint_trajectory
   action_ns: ""
   type: FollowJointTrajectory
   joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

 - name: gripper_action
   action_ns: ""
   type: GripperCommand
   default: true
   command_joint: robotiq_85_left_knuckle_joint
   joints:
      - robotiq_85_left_knuckle_joint

